import { StyleSheet } from "react-native";
import colors from "../components/colors";

module.exports = StyleSheet.create({
    container: {
        flex: 1,
        padding: 0,
    },
    itemContainer: {
        paddingVertical: 5,
        paddingHorizontal: 15,
        marginVertical: 0,
        backgroundColor: colors.white,
        // backgroundColor: colors.lightergray,
        borderColor: colors.lightgray,
        borderWidth: 1,
        direction: 'rtl',
    },
    deviceName: {
        fontSize: 14,
        marginBottom: 2,
        fontFamily: 'iransansbold',
        direction: 'rtl',
        color: colors.darkBackground,
        textAlign: 'right',
    },
    damageTitle: {
        fontSize: 12,
        fontFamily: 'iransansbold',
        color: colors.gray,
        textAlign: 'right',
    },
    textTitle: {
        fontSize: 12,
        fontFamily: 'iransansbold',
        color: colors.darkblue,
        textAlign: 'right',
        marginTop: 5,
    },
    date: {
        position: 'absolute',
        top: 35,
        left: 20,
        fontFamily: 'iransans',
        fontSize: 12,
    },
    stateView: {
        position: 'absolute',
        top: 15,
        left: 20,
        flexDirection: 'row-reverse',
        alignContent: 'center',
        alignItems: 'center',
    },
    stateCircle: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    pilotIcon: {
        color: colors.red3,
        fontSize: 15,
    },
    state: {
        fontFamily: 'iransans',
        fontSize: 11,
        paddingLeft: 10,
    },
    filterButton: {
        // backgroundColor: colors.blue,
        borderRadius: 7,
        marginRight: 6,
    },
    filterButtonIcon: {
        // color: colors.white,
        color: colors.text,
        fontSize: 16,
        paddingVertical: 7,
        paddingHorizontal: 10,
    },
    filterView: {
        backgroundColor: colors.lightBackground,
        paddingVertical: 10,
    },
    filterRow: {
        flexDirection: 'row-reverse',
        alignContent: 'center',
        alignItems: 'center',
        paddingVertical: 4,
    },
    label: {
        padding: 0,
        fontFamily: 'iransans',
        fontSize: 12,
        margin: 0,
        width: '15%',
        marginHorizontal: 5,
        textAlign: 'center',
        color: colors.text,
    },
    textInput4: {
        padding: 0,
        fontFamily: 'iransans',
        fontSize: 12,
        paddingVertical: 1,
        borderRadius: 7,
        margin: 0,
        width: '30%',
        marginHorizontal: 5,
        textAlign: 'right',
        paddingHorizontal: 10,
        backgroundColor: colors.white,
        color: colors.black,
    },
    dateInputButton: {
        paddingVertical: 4,
        marginTop: 5,
        borderRadius: 7,
        width: '30%',
        marginHorizontal: 5,
        paddingHorizontal: 10,
        backgroundColor: colors.white,
        flexDirection: 'row-reverse',
    },
    dateInputButtonText: {
        fontFamily: 'iransans',
        fontSize: 12,
        borderRadius: 7,
        margin: 0,
        textAlign: 'right',
        color: colors.black,
    },
    workflowFilter: {
        paddingVertical: 4,
        marginTop: 5,
        borderRadius: 7,
        width: '80%',
        marginHorizontal: 5,
        paddingHorizontal: 10,
        backgroundColor: colors.white,
        flexDirection: 'row-reverse',
    },
    workflowFilterText: {
        fontFamily: 'iransans',
        fontSize: 12,
        borderRadius: 7,
        margin: 0,
        textAlign: 'right',
        color: colors.black,
    },
    filterBtn: {
        flexDirection: 'row-reverse',
        justifyContent: 'center',
        width: '40%',
        marginHorizontal: '5%',
        borderRadius: 7,
        marginTop: 10,
    },
    filterBtnIcon: {
        color: colors.white,
        fontSize: 13,
        paddingTop: 8,
        paddingLeft: 10,
    },
    filterBtnText: {
        fontFamily: 'iransans',
        fontSize: 13,
        color: colors.white,
        paddingVertical: 5,
    },
    buttonsView: {
        flexDirection: 'row-reverse',
        paddingRight: 10,
        justifyContent: 'center',
    },
    callbuttonsView: {
        position: 'absolute',
        zIndex: 10,
        bottom: 10,
        left: 15,
        flexDirection: 'row',
    },
    callButton: {
        marginRight: 15,
        borderRadius: 35 / 2,
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
    },
    callIcon: {
        color: colors.pacificcyan,
        fontSize: 25
    },
    sectionSplitter: {
        textAlign: 'center',
        fontFamily: 'iransansbold',
        fontSize: 13,
        paddingVertical: 1,
        margin: 0,
        // fontWeight: 'bold',
    },
    
});