import api from '../config/api';
import { use_local_data } from '../config/consts';

export const submitInstallRequest = async (skip, take) => {
    try {
        if (use_local_data) return {
            success: true, data: {
                "Data": [
                    {
                        "customerName": "پاسارگاد",
                        "branchName": "شعبه اردبیل",
                        "preInstallTitle": "تست تجهیز موجود",
                        "serviceName": "اصلاح وضعیت نصب",
                        "deviceSerial": null,
                        "modelTitle": "-",
                        "id": 233500,
                        "preInstallationId": 193086,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "بازدید اولیه محل نصب ",
                        "lastState": "OfficeView",
                        "requestId": 991167,
                        "persianLastState": "مشاهده مدیر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021020104422,
                        "persianStartDate": "1402/10/20",
                        "endDate": null,
                        "requestDeadLine": 14021022170000,
                        "persianRequestDeadLine": "1402/10/22",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "پاسارگاد (باجه)",
                        "branchName": "سرپرستی تهران و البرز",
                        "preInstallTitle": "نصب دستگاه جدید",
                        "serviceName": "نصب و راه اندازی تجهیز",
                        "deviceSerial": null,
                        "modelTitle": "Eastcom 285",
                        "id": 233499,
                        "preInstallationId": 193085,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "حمل و تحویل ",
                        "lastState": "SendToOffice",
                        "requestId": 991166,
                        "persianLastState": "ارجاع به دفتر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021019142550,
                        "persianStartDate": "1402/10/19",
                        "endDate": null,
                        "requestDeadLine": 14021021170000,
                        "persianRequestDeadLine": "1402/10/21",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "پاسارگاد (باجه)",
                        "branchName": "سرپرستی تهران و البرز",
                        "preInstallTitle": "نصب دستگاه جدید",
                        "serviceName": "نصب و راه اندازی تجهیز",
                        "deviceSerial": null,
                        "modelTitle": "Eastcom 285",
                        "id": 233498,
                        "preInstallationId": 193085,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "راه اندازی تجهیز",
                        "lastState": "SendToOffice",
                        "requestId": 991165,
                        "persianLastState": "ارجاع به دفتر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021019142550,
                        "persianStartDate": "1402/10/19",
                        "endDate": null,
                        "requestDeadLine": 14021021170000,
                        "persianRequestDeadLine": "1402/10/21",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "پاسارگاد (باجه)",
                        "branchName": "سرپرستی تهران و البرز",
                        "preInstallTitle": "نصب دستگاه جدید",
                        "serviceName": "نصب و راه اندازی تجهیز",
                        "deviceSerial": null,
                        "modelTitle": "Eastcom 285",
                        "id": 233497,
                        "preInstallationId": 193085,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "نصب فیزیکی",
                        "lastState": "SendToOffice",
                        "requestId": 991164,
                        "persianLastState": "ارجاع به دفتر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021019142550,
                        "persianStartDate": "1402/10/19",
                        "endDate": null,
                        "requestDeadLine": 14021021170000,
                        "persianRequestDeadLine": "1402/10/21",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "پاسارگاد (باجه)",
                        "branchName": "سرپرستی تهران و البرز",
                        "preInstallTitle": "نصب دستگاه جدید",
                        "serviceName": "نصب و راه اندازی تجهیز",
                        "deviceSerial": null,
                        "modelTitle": "Eastcom 285",
                        "id": 233496,
                        "preInstallationId": 193085,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "جابجایی",
                        "lastState": "SendToOffice",
                        "requestId": 991163,
                        "persianLastState": "ارجاع به دفتر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021019142549,
                        "persianStartDate": "1402/10/19",
                        "endDate": null,
                        "requestDeadLine": 14021021170000,
                        "persianRequestDeadLine": "1402/10/21",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "سامان",
                        "branchName": "اداره توزیع و جمع آوری نقود",
                        "preInstallTitle": "تست",
                        "serviceName": "انتقال از یک محل به محل دیگر",
                        "deviceSerial": "56BT301117",
                        "modelTitle": "Eastcom 2000 Xe USB",
                        "id": 223505,
                        "preInstallationId": 183087,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "حمل و تحویل ",
                        "lastState": "Acting",
                        "requestId": 981173,
                        "persianLastState": "در حال اقدام",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 1,
                        "startDate": 14021016120823,
                        "persianStartDate": "1402/10/16",
                        "endDate": null,
                        "requestDeadLine": 14021019170000,
                        "persianRequestDeadLine": "1402/10/19",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "سامان",
                        "branchName": "اداره توزیع و جمع آوری نقود",
                        "preInstallTitle": "تست",
                        "serviceName": "انتقال از یک محل به محل دیگر",
                        "deviceSerial": "56BT301117",
                        "modelTitle": "Eastcom 2000 Xe USB",
                        "id": 223504,
                        "preInstallationId": 183087,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "جابجایی",
                        "lastState": "SendToOffice",
                        "requestId": 981172,
                        "persianLastState": "ارجاع به دفتر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021016120823,
                        "persianStartDate": "1402/10/16",
                        "endDate": null,
                        "requestDeadLine": 14021019170000,
                        "persianRequestDeadLine": "1402/10/19",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "سامان",
                        "branchName": "اداره توزیع و جمع آوری نقود",
                        "preInstallTitle": "تست",
                        "serviceName": "انتقال از یک محل به محل دیگر",
                        "deviceSerial": "56BT301117",
                        "modelTitle": "Eastcom 2000 Xe USB",
                        "id": 223503,
                        "preInstallationId": 183087,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "راه اندازی تجهیز",
                        "lastState": "DoneExpert",
                        "requestId": 981171,
                        "persianLastState": "بستن کارشناس",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021016120823,
                        "persianStartDate": "1402/10/16",
                        "endDate": null,
                        "requestDeadLine": 14021019170000,
                        "persianRequestDeadLine": "1402/10/19",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    },
                    {
                        "customerName": "سامان",
                        "branchName": "اداره توزیع و جمع آوری نقود",
                        "preInstallTitle": "تست",
                        "serviceName": "انتقال از یک محل به محل دیگر",
                        "deviceSerial": "56BT301117",
                        "modelTitle": "Eastcom 2000 Xe USB",
                        "id": 223502,
                        "preInstallationId": 183087,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "فرزانه وفا",
                        "installationServiceName": "نصب فیزیکی",
                        "lastState": "CancelOffice",
                        "requestId": 981170,
                        "persianLastState": "تایید کنسل توسط مدیر",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021016120823,
                        "persianStartDate": "1402/10/16",
                        "endDate": 14021016122151,
                        "requestDeadLine": 14021019170000,
                        "persianRequestDeadLine": "1402/10/19",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 0
                    },
                    {
                        "customerName": "سامان",
                        "branchName": "اداره توزیع و جمع آوری نقود",
                        "preInstallTitle": "تست",
                        "serviceName": "انتقال از یک محل به محل دیگر",
                        "deviceSerial": "56BT301117",
                        "modelTitle": "Eastcom 2000 Xe USB",
                        "id": 223501,
                        "preInstallationId": 183087,
                        "AreaName": "دفتر غرب تهران",
                        "SDAreaName": "دفتر غرب تهران/ندارد",
                        "operationalAreaName": "دفتر غرب تهران",
                        "currentUserName": "حسین صبوری",
                        "installationServiceName": "جمع آوری",
                        "lastState": "DoneExpert",
                        "requestId": 981169,
                        "persianLastState": "بستن کارشناس",
                        "ConstraintId": 26,
                        "UserName": "1059",
                        "reportHasFile": 0,
                        "startDate": 14021016120823,
                        "persianStartDate": "1402/10/16",
                        "endDate": null,
                        "requestDeadLine": 14021019170000,
                        "persianRequestDeadLine": "1402/10/19",
                        "state": "Start",
                        "persianState": "درحال انجام",
                        "SLAStyle": 150
                    }
                ],
                "TotalCount": 168
            }
        }
        const response = await api.post('/InstallationRequest/LoadAllInstallationRequestList', { "skip": skip, "take": take, "sort": [{ "field": "id", "dir": "desc" }], "filter": { "logic": "and", "filters": [{ "field": "IsArchived", "operator": "Eq", "value": 0 }] } });
        return { success: true, data: response.data };
    } catch (error) {
        console.log('Error submitting LoadAllInstallationRequestList request:', error);
        return { success: false, error: 'Failed to submit LoadAllInstallationRequestList request' };
    }
};


